Repository Indie-Kart/ecommerce-store, pull requests merged in 2024-05, with the labels that each got.

#35 year needs to update dynamic in footer section #33
  components/footer.tsx
Labels: bug, level2, gssoc

#40 Added hover effect when hovering on a product card (#38).
  components/ui/product-card.tsx
Labels: good first issue, level1, gssoc

#42 Update PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: documentation, gssoc

#49 Created documentation.yml
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: level1, gssoc

#61 added animated cursor
  .env
  app/(routes)/page.tsx
  app/(routes)/product/[productId]/page.tsx
  app/layout.tsx
  components/product-list.tsx
  package-lock.json
  package.json
Labels: good first issue, level1, gssoc

#59 Signup login
  app/login/page.tsx
  app/signup/page.tsx
Labels: enhancement, level2, gssoc

#68 Empty state cart
  app/(routes)/cart/page.tsx
  json/empty_cart.json
  package-lock.json
  package.json
Labels: enhancement, good first issue, level1, gssoc

#79 Banner swiper
  app/(routes)/page.tsx
  components/ui/billboard.tsx
  package-lock.json
  package.json
  types.ts
Labels: good first issue, level1, gssoc

#83 add share functionality
  components/info.tsx
Labels: enhancement, level1, gssoc
