Repository Indie-Kart/ecommerce-store, pull requests merged in 2024-07, with the labels that each got.

#186 [Feature] : Cart page Product Quantity
  app/(routes)/cart/components/cart-item.tsx
  app/(routes)/cart/components/summary.tsx
  app/(routes)/cart/page.tsx
Labels: level2, gssoc

#191 [Feature]: Share options Added
  .env
  app/(routes)/product/[productId]/page.tsx
  components/info.tsx
Labels: level1, gssoc

#202 Fix multiple issues related to Next.js module resolution, CartItemPro…
  app/(routes)/cart/components/cart-item-info.tsx
  app/(routes)/cart/components/cart-item.tsx
  app/(routes)/cart/components/summary.tsx
  app/(routes)/cart/page.tsx
  app/[...not_found]/page.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: level2, gssoc

#204 Added Back-To-Top Button
  app/(routes)/page.tsx
  app/(routes)/product/[productId]/page.tsx
  app/(routes)/wishlist/page.tsx
  app/layout.tsx
  components/gallery/gallery-tab.tsx
  components/ui/BacktoTop.tsx
  package.json
Labels: gssoc

#209 [BUG]: Cart page item removed prize not change fixed
  app/(routes)/cart/components/cart-item.tsx
  app/(routes)/cart/page.tsx
  package-lock.json
Labels: level1, gssoc

#214 Added "Cursor Trail Effect" to Website
  app/globals.css
  app/layout.tsx
  components/CursorTrail.tsx
Labels: VSoC'24, MEDIUM

#220 Update README.md
  README.md
Labels: VSoC'24, EASY

#219 Enhanced Readme.md
  README.md
Labels: gssoc
