Repository Indie-Kart/ecommerce-store, pull requests merged in 2024-06, with the labels that each got.

#90 Add Directly remove Item from item page
  components/info.tsx
  components/ui/product-card.tsx
Labels: enhancement, level2, gssoc

#87 Filter price
  actions/PriceFilter.tsx
  actions/get-products.tsx
  app/(routes)/category/[categoryId]/page.tsx
  types.ts
Labels: enhancement, good first issue, level1, gssoc

#57 Fix issue #53 Fixed Navbar
  app/(routes)/cart/page.tsx
  app/(routes)/category/[categoryId]/page.tsx
  app/(routes)/page.tsx
  app/(routes)/product/[productId]/page.tsx
  components/navbar.tsx
  components/ui/billboard.tsx
  package-lock.json
  package.json
Labels: level2, gssoc

#136 added new feature in signup and sign in page
  app/login/page.tsx
  app/signup/page.tsx
  package-lock.json
  package.json
Labels: VSoC'24, HARD

#151 added login button and route through login page
  app/login/page.tsx
  components/navbar.tsx
  package-lock.json
Labels: VSoC'24, EASY

#172 Feat: 404 notfound page added with config
  app/[...not_found]/page.tsx
  app/not-found.tsx
  public/404.png
Labels: level1, gssoc

#178 Add GitHub auth
  .env
  PULL_REQUEST_TEMPLATE.md
  actions/PriceFilter.tsx
  actions/get-products.tsx
  app/(routes)/cart/components/cart-item-info.tsx
  app/(routes)/cart/components/cart-item.tsx
  app/(routes)/cart/components/summary.tsx
  app/(routes)/cart/page.tsx
  app/(routes)/category/[categoryId]/components/filter.tsx
  app/(routes)/category/[categoryId]/components/mobile-filters.tsx
  app/(routes)/category/[categoryId]/page.tsx
  app/(routes)/chatboticon.tsx
  app/(routes)/chatbotmodel.tsx
  app/(routes)/loading.tsx
  app/(routes)/page.tsx
  app/(routes)/product/[productId]/loading.tsx
  app/api/auth/[...nextauth]/route.ts
  app/globals.css
  app/login/page.tsx
  app/signup/page.tsx
  auth.d.ts
  auth.ts
  components/auth-components.tsx
  components/footer.tsx
  components/info.tsx
  components/main-nav.tsx
  components/navbar-actions.tsx
  components/navbar.tsx
  components/preview-modal.tsx
  components/product-list.tsx
  components/ui/avatar.tsx
  components/ui/button.tsx
  components/ui/dropdown-menu.tsx
  components/ui/product-card.tsx
  components/user-button.tsx
  constants.ts
  hooks/use-cart.tsx
  hooks/use-preview-modal.ts
  hooks/use-wishlist.tsx
  json/empty_cart.json
  middleware.ts
  package-lock.json
  package.json
  tailwind.config.js
  tsconfig.json
  types.ts
Labels: level3, gssoc
